services:
    rest_api:
        container_name: rest_api_pi2
        build: ./server
        ports:
            - "5000:5000"
        networks:
            pi2_network:
                ipv4_address: 172.30.0.10 
        depends_on: 
            - database
    chat:
        container_name: chat_pi2
        build: ./chat
        ports:
            - "8080:8080"
        networks: 
            pi2_network:
                ipv4_address: 172.30.0.11
        depends_on: 
            - database
    database:
        container_name: bd_pi2
        image: "mysql:8"
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=rede_social
            - MYSQL_ROOT_PASSWORD=1234
        networks:
            pi2_network:
                ipv4_address: 172.30.0.12
    frontend:
        container_name: frontend_pi2
        build: ./client
        ports:
            - "3000:3000"
        networks:
            pi2_network:
                ipv4_address: 172.30.0.13
        depends_on: 
            - chat
            - rest_api
networks:
    pi2_network:
        ipam:
            driver: default
            config:
                - subnet: "172.30.0.0/24"
                  gateway: "172.30.0.1"                
