services:
  rest_api:
    container_name: rest_api_pi2
    build: ./server
    ports:
      - "5000:5000"
    depends_on: 
      - database
      
  chat:
    container_name: chat_pi2
    build: ./chat
    ports:
      - "8080:8080"
    depends_on: 
      - database
      - cache

  database:
    container_name: bd_pi2
    image: "mysql:8"
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=rede_social
      - MYSQL_ROOT_PASSWORD=1234
   
  frontend:
    container_name: frontend_pi2
    build: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - chat
      - rest_api

  cache:
    container_name: memcached_pi2
    image: "memcached:1.6.22"
    ports:
      - "11211:11211"
   
